"""Add word to piece.

Revision ID: 1f618a36c705
Revises: 304aff514702
Create Date: 2015-09-17 11:46:57.511947

"""

# revision identifiers, used by Alembic.
revision = '1f618a36c705'
down_revision = '304aff514702'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('word_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'piece', 'word', ['word_id'], ['id'])
    op.drop_column('piece', 'word')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('word', mysql.VARCHAR(length=50), nullable=False))
    op.drop_constraint(None, 'piece', type_='foreignkey')
    op.drop_column('piece', 'word_id')
    ### end Alembic commands ###
