"""Update notification.

Revision ID: 1cc7271279f8
Revises: 1f618a36c705
Create Date: 2015-09-22 17:56:02.954541

"""

# revision identifiers, used by Alembic.
revision = '1cc7271279f8'
down_revision = '1f618a36c705'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('piece_comment_id', sa.Integer(), nullable=True))
    op.add_column('notification', sa.Column('piece_id', sa.Integer(), nullable=True))
    op.add_column('notification', sa.Column('senders_list', sa.Text(), nullable=True))
    op.add_column('notification', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'notification_ibfk_2', 'notification', type_='foreignkey')
    op.drop_constraint(u'notification_ibfk_1', 'notification', type_='foreignkey')
    op.create_foreign_key(None, 'notification', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'notification', 'piece_comment', ['piece_comment_id'], ['id'])
    op.create_foreign_key(None, 'notification', 'piece', ['piece_id'], ['id'])
    op.drop_column('notification', 'content')
    op.drop_column('notification', 'link')
    op.drop_column('notification', 'receiver_id')
    op.drop_column('notification', 'sender_id')
    op.drop_column('notification', 'target')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification', sa.Column('target', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('notification', sa.Column('sender_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('notification', sa.Column('receiver_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('notification', sa.Column('link', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('notification', sa.Column('content', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.drop_constraint(None, 'notification', type_='foreignkey')
    op.create_foreign_key(u'notification_ibfk_1', 'notification', 'user', ['receiver_id'], ['id'])
    op.create_foreign_key(u'notification_ibfk_2', 'notification', 'user', ['sender_id'], ['id'])
    op.drop_column('notification', 'user_id')
    op.drop_column('notification', 'senders_list')
    op.drop_column('notification', 'piece_id')
    op.drop_column('notification', 'piece_comment_id')
    ### end Alembic commands ###
