"""Add Word model.

Revision ID: 304aff514702
Revises: 745a6fade6
Create Date: 2015-09-14 11:02:42.451629

"""

# revision identifiers, used by Alembic.
revision = '304aff514702'
down_revision = '745a6fade6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('first_letter', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word')
    ### end Alembic commands ###
