"""Update db.

Revision ID: 36bd1e3d0de9
Revises: 1cc7271279f8
Create Date: 2015-09-22 19:08:02.498531

"""

# revision identifiers, used by Alembic.
revision = '36bd1e3d0de9'
down_revision = '1cc7271279f8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_like')
    op.drop_table('invitation_code')
    op.drop_table('collection_piece')
    op.drop_table('collection_edit_log_report')
    op.drop_table('collection_edit_log')
    op.drop_table('click_log')
    op.drop_table('collection')
    op.drop_table('collection_kind')
    op.drop_table('piece_author')
    op.drop_table('sentence')
    op.drop_table('piece_edit_log_report')
    op.drop_table('search_log')
    op.drop_table('mail_log')
    op.drop_table('piece_source')
    op.drop_table('piece_edit_log')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_edit_log',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('kind', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('before', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('before_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('after', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('after_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('compare', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('collection_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], [u'collection.id'], name=u'collection_edit_log_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'collection_edit_log_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('collection_kind',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('show_order', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('invitation_code',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('sended_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sender_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], [u'user.id'], name=u'invitation_code_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'invitation_code_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('collection_like',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('collection_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], [u'collection.id'], name=u'collection_like_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'collection_like_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('piece_edit_log',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('piece_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('kind', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('after', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('after_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('before', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('before_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('compare', mysql.VARCHAR(length=500), nullable=True),
    sa.ForeignKeyConstraint(['piece_id'], [u'piece.id'], name=u'piece_edit_log_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'piece_edit_log_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('piece_source',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('mail_log',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('search_log',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('keyword', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'search_log_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('collection_edit_log_report',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('log_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('processed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['log_id'], [u'collection_edit_log.id'], name=u'collection_edit_log_report_ibfk_3'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'collection_edit_log_report_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('piece_edit_log_report',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('processed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('log_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['log_id'], [u'piece_edit_log.id'], name=u'piece_edit_log_report_ibfk_3'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'piece_edit_log_report_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('sentence',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('piece_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['piece_id'], [u'piece.id'], name=u'sentence_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'sentence_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('piece_author',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('collection',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('cover', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('desc', mysql.TEXT(), nullable=True),
    sa.Column('kind_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('locked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['kind_id'], [u'collection_kind.id'], name=u'collection_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'collection_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('click_log',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'click_log_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('collection_piece',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('collection_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('piece_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], [u'collection.id'], name=u'collection_piece_ibfk_1'),
    sa.ForeignKeyConstraint(['piece_id'], [u'piece.id'], name=u'collection_piece_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
