"""Update Piece and Add Sentence.

Revision ID: 5ab6b37da4d1
Revises: 49086f55444e
Create Date: 2015-09-05 10:33:58.017796

"""

# revision identifiers, used by Alembic.
revision = '5ab6b37da4d1'
down_revision = '49086f55444e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('piece_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'piece', sa.Column('word', sa.String(length=50), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'piece', 'word')
    op.drop_table('sentence')
    ### end Alembic commands ###
