"""Update Piece model.

Revision ID: 745a6fade6
Revises: 23c5ee2b5f11
Create Date: 2015-09-14 11:00:35.602846

"""

# revision identifiers, used by Alembic.
revision = '745a6fade6'
down_revision = '23c5ee2b5f11'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('piece', sa.Column('sentence', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('piece', 'sentence')
    ### end Alembic commands ###
