"""Update User model.

Revision ID: 23c5ee2b5f11
Revises: a1681f8b936
Create Date: 2015-09-05 11:25:41.166691

"""

# revision identifiers, used by Alembic.
revision = '23c5ee2b5f11'
down_revision = 'a1681f8b936'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('receive_comments_notification', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('receive_votes_notification', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'receive_votes_notification')
    op.drop_column('user', 'receive_comments_notification')
    ### end Alembic commands ###
